name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4.1.1

      
